param(
    [Parameter(Mandatory = $true)]
    $Context
)

$ErrorActionPreference = "Stop"

Write-Step "Configuring mise Runtimes"

# 说明：
#   这一步只在 mise 已安装时执行。

# 行为规则：
#   1. 如果 mise 不存在，直接跳过
#   2. 如果本地已经有 mise config.toml，则绝不覆盖，直接使用现有配置执行 mise install
#   3. 如果本地没有 config.toml，且 windows.runtimes.json 非空，则生成一个最小临时 config
#   4. 如果本地没有 config.toml，且 runtimes 为空，则直接跳过

# 原因：
#   - bootstrap 不抢占 chezmoi 未来要管理的 mise 配置
#   - 但在“还没 apply chezmoi、又确实声明了 runtimes”的情况下，仍能临时工作

if (-not (Test-CommandExists "mise")) {
    Write-Host "  mise is not installed; skipping runtime setup." -ForegroundColor DarkGray
    Write-OK "mise step skipped"
    return
}

$windowsRuntimes = $Context.WindowsRuntimes
if ($null -eq $windowsRuntimes) {
    Write-Warn "Context.WindowsRuntimes is null; skipping mise step."
    return
}

$runtimes = @()
if ($windowsRuntimes.PSObject.Properties["runtimes"] -and $null -ne $windowsRuntimes.runtimes) {
    $runtimes = @(
        $windowsRuntimes.runtimes |
        ForEach-Object { [string]$_ } |
        Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
    )
}

$miseConfigRoot = if ($env:XDG_CONFIG_HOME) {
    Join-Path $env:XDG_CONFIG_HOME "mise"
} else {
    Join-Path $env:USERPROFILE ".config\mise"
}

Ensure-DirectoryExists -Path $miseConfigRoot
$miseConfigPath = Join-Path $miseConfigRoot "config.toml"

$hasExistingConfig = Test-Path $miseConfigPath

if ($hasExistingConfig) {
    Write-Host "  Existing mise config detected: $miseConfigPath" -ForegroundColor DarkGray
    Write-Host "  Keeping existing config (will not overwrite)." -ForegroundColor DarkGray
} elseif ($runtimes.Count -eq 0) {
    Write-Host "  No runtimes declared and no existing mise config found; skipping mise setup." -ForegroundColor DarkGray
    Write-OK "mise step skipped"
    return
} else {
    Write-Host "  No mise config found; generating minimal config from windows.runtimes.json" -ForegroundColor Gray

    $toolLines = foreach ($runtime in $runtimes) {
        $parts = $runtime -split "@", 2
        $toolName = $parts[0]
        $toolVersion = if ($parts.Count -gt 1 -and -not [string]::IsNullOrWhiteSpace($parts[1])) {
            $parts[1]
        } else {
            "latest"
        }

        '{0} = "{1}"' -f $toolName, $toolVersion
    }

    $configContent = @(
        '# Auto-generated by scripts/steps/40-mise.ps1'
        '# This file is only created when no existing mise config is present.'
        '# Once chezmoi manages ~/.config/mise/config.toml, bootstrap will stop overwriting it.'
        ''
        '[tools]'
    ) + $toolLines

    Set-Content -Path $miseConfigPath -Value ($configContent -join "`r`n") -Encoding UTF8
    Write-OK "Temporary mise config created"
}

Update-PathEnvironment

Write-Host "  Installing runtimes via mise..." -ForegroundColor Gray
try {
    mise install
    Write-OK "mise install complete"
} catch {
    throw "mise install failed: $_"
}

try {
    mise reshim
    Write-OK "mise reshim complete"
} catch {
    Write-Warn "mise reshim failed or is not required: $_"
}

Update-PathEnvironment

# 只有声明了 runtimes 时，才做命令级验证。
# 如果使用的是用户已有 config，则不强制假设 windows.runtimes.json 一定列全了所有工具。
if ($runtimes.Count -gt 0) {
    Test-MiseRuntimeCommands -RuntimeSpecs $runtimes
} else {
    Write-Host "  Skipping runtime command validation because windows.runtimes.json is empty." -ForegroundColor DarkGray
}

Write-OK "mise step complete"
