# espanso configuration file

yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json

# 有关完整介绍，请访问官方文档： https://espanso.org/docs/

# 您可以使用此文件来定义 espanso 的全局配置选项。
# 这些参数将在每个应用程序上默认使用，
# 但您也可以在每个应用程序级别覆盖它们。

# 为了便于定制，此文件包含一些常用参数。
# 随意取消注释并调整它们以满足您的需求！

# --- Toggle key

# 自定义用于（双击时）禁用和启用 espanso 的按键
# 可用选项：CTRL、SHIFT、ALT、CMD、OFF
# 你也可以指定按键变体，例如 LEFT_CTRL、RIGHT_SHIFT 等...
# toggle_key：RIGHT_CTRL
# 你也可以通过以下方式完全禁用切换按键
# toggle_key：OFF

# --- Injection Backend

# Espanso 支持多种将文本注入应用程序的方法。每种方法都有其特殊性，因此如果遇到问题，你可能需要更改它。
# 默认情况下，espanso 使用“自动”后端，在大多数情况下应能正常工作，但如果出现问题，你可以尝试“剪贴板”或“注入”后端。
# backend: Clipboard

# --- Auto-restart

# 在检测到文件更改后启用/禁用配置自动重新加载。
auto_restart: true

# --- Clipboard threshold

# 因为逐字符注入长文本是一个缓慢的操作，espanso 会在文本长度超过 ''clipboard_threshold'' 字符时自动使用剪贴板。
clipboard_threshold: 30

# --- Regex Buffer Size

# 用于正则触发器的最大内存字符数。
# 此值决定了 espanso 可匹配的正则触发器的最大长度，默认值为 30 个字符。
# 建议将此值保持在合理的较低水平。
# 如果您有非常长的触发器，可以考虑增加此值，但会增加内存使用。
# max_regex_buffer_size: 30

# 有关所有可用选项的列表，请访问官方文档： https://espanso.org/docs/

backspace_limit: 5
# 自定义搜索快捷键
search_shortcut: ALT+SHIFT+SPACE
