# vim: ft=dosini
[Metadata]
Name=Catppuccin Mocha Mauve
Version=1.0
Author=prettycation
Description=Catppuccin Mocha using Fcitx5 standard variables
ScaleWithDPI=True

[InputPanel]
# 字体
Font=Sans 13
# 候选项间距
Spacing=3
# 页面按钮对齐
PageButtonAlignment="Last Candidate"

# --- 文字颜色配置 ---

# 普通文字颜色 (Rime: candidate_text_color, label_color, comment_text_color, hilited_text_color )
# Fcitx5 中序号和注释共享此颜色
NormalColor=#cdd6f4

# 选中候选项的文字颜色 (选中后的文字、序号、注释均变为此色)
# 对应 Rime: hilited_candidate_text_color (0x2e1e1e -> #1e1e2e)
HighlightCandidateColor=#1e1e2e

[InputPanel/Background]
# 主背景颜色 (Rime: back_color 0x1B1111 -> #11111b)
Color=#11111b
# 边框
BorderColor=#313244
BorderWidth=2
# 您的原始切图
Image=panel.svg

[InputPanel/Background/Margin]
Left=10
Right=10
Top=10
Bottom=10

[InputPanel/Highlight]
# 选中项背景颜色 (Rime: hilited_candidate_back_color 0xf7a6cb -> #cba6f7)
Color=#cba6f7
# 高亮切图
Image=highlight.svg

[InputPanel/Highlight/Margin]
# 左右边距调大，使高亮色块缩短成“胶囊”状
Left=18
Right=18
# 上下边距调整高度
Top=8
Bottom=8

[InputPanel/TextMargin]
Left=18
Right=18
Top=8
Bottom=8

[Menu]
Font=Sans 10
# 菜单普通文字
NormalColor=#cdd6f4
# 菜单选中项文字
HighlightCandidateColor=#1e1e2e
Spacing=3

[Menu/Background]
Color=#11111b
Image=
BorderColor=#313244
BorderWidth=2

[Menu/Highlight]
# 菜单选中项背景
Color=#f5c2e7

[Menu/Separator]
# 分隔线颜色 (对应 Rime: border_color)
Color=#1e1e2e

[Menu/CheckBox]
# 单选框图标
Image=radio.png

[Menu/SubMenu]
# 子菜单箭头图标
Image=arrow.png

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5
